# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 644dc5b509fd886562f8aefb1488f4342b41b21e614634b2b561e16a06d217237a0c740ef5cab8cdb027fa4e161b4d2df1b54ed5dfc2685221e8801510bf7d3c

test:
  secret_key_base: 7fa3fcb473fba01fe1a1ff1e70b0aa6b0e3855aa61f5a7fb3e1736066f7c904b46d7f70c01a960d1ea915705be4c5e6fd1cb5d336b6f4e62169a06892d1bc7de

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
